version: "3.8"
services:
  gluecksrad-app:
    build: .
    container_name: dgr_app
    # Wir publishen Port 443, da Node am Ende HTTPS auf 443 macht
    ports:
      - "443:443"
      - "80:80"
    # Port 80: acme.sh Standalone-Modus => wir übernehmen es in start.sh
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ACME_EMAIL=${ACME_EMAIL}
    volumes:
      - ./acme-data:/acme-data
    # netzwerk an default
    restart: unless-stopped
