version: "3.8"
services:
  gluecksrad-app:
    build: .
    container_name: dgr_app
    depends_on:
      - dgr_nginx
    environment:
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      NODE_ENV: production
    volumes:
      - ./dbdata:/app/database
    expose:
      - "3000"

  dgr_nginx:
    image: nginx:alpine
    container_name: dgr_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: dgr_certbot
    depends_on:
      - dgr_nginx
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    entrypoint: /bin/sh
    # run manually => e.g.:
    # docker-compose run --rm certbot certonly --webroot -w /var/www/certbot ...
